### DISCUSSION TITLE
PAC CLI pages upload data model error

### DISCUSSION THREAD

**Discussion by jbuenoliveira** [microsoft/powerplatform-build-tools#1037] [General]
@mikevalentinecanteen  / @tehcrashxor / @vikaskumarsingh123 
We need to re-open the issue because it has recurred. Ref.: #897

> Error: Power Pages entities for standard data model (v1) aren't available on this org, please install required packages on this org. If you are trying to upload to enhanced data model (v2), pass model version as "2". For more information see https://learn.microsoft.com/en-us/power-pages/admin/enhanced-data-model#data-model-power-platform-cli-parameters.

via Power Platform Build Tools: **v2.0.77 (latest) [w/ PAC CLI: v1.34]**

Our current Partner Portal uses the standard data model, and we are not migrating to the enhanced data model yet. Additionally, the toggle for the enhanced data model is currently OFF in all environments.
![image](https://github.com/user-attachments/assets/1c7b5397-cbc7-4744-a22d-132c6258998a)

And we are specifying through our pipelines that we are using model version 1:
```YAML
- task: PowerPlatformUploadPaportal@2
   inputs:
     authenticationType: 'PowerPlatformSPN'
     PowerPlatformSPN: '$(EnvironmentSPN)'
     UploadPath: '$(PortalSrcPath)'
     Environment: '$(EnvironmentUrl)'
     ModelVersion: '1'
```

Are we missing something? Has there been a recent update, perhaps related to Wave 2, that could be affecting this?

Thank you in advance for your time.
