### DISCUSSION TITLE
GitHub Actions Workflow Failure when trying to import a solution to the Power Platform - CanvasApp Import Error: MismatchingLogicalNames

### DISCUSSION THREAD

**Discussion by priyanka-agrawal2885** [microsoft/powerplatform-build-tools#1161] [Q&A]
Hi Team,

I am reaching out to seek help on a GitHub Actions workflow failure when we are trying to import a solution to the Power Platform. We have a set of workflows that first exports a solution from Power Platform from the dev environment and then imports it to the testing and production environment. We have configured them as reusable workflows since all the Power Platform solutions follow the same process. Strangely, the workflows are running successfully for all the other solutions except one.

The solution first gets exported from the Power Platform as an unmanaged solution using the following workflow:

```
name: Export Solution
on:
  workflow_call:
    inputs:
      issue-key:
        required: true
        type: string
jobs:
  export:
    runs-on: windows-latest
    environment: 
        name: 'DEV'
    steps:
    
      - name: Configure Git for long paths
        run: git config --global core.longpaths true
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download/install pac CLI
        run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

      - name: Authentication using pac cli
        run: pac auth create --environment "${{ secrets.ENVIRONMENT_URL }}" --username "${{ secrets.POWERPLATFORM_USERNAME }}" --password "${{ secrets.POWERPLATFORM_PASSWORD }}"

      - name: Export Managed Solution
        run: pac solution export --environment "${{ secrets.ENVIRONMENT_URL }}" --path bin/${{ secrets.SOLUTION_NAME }}.zip --name "${{ secrets.SOLUTION_NAME }}" --managed false --async true

      - name: Unpack solution
        run: pac solution unpack --zipfile bin/${{ secrets.SOLUTION_NAME }}.zip --folder out/${{ secrets.SOLUTION_NAME }} --packageType Unmanaged --errorlevel Info --singleComponent None --useLcid false --useUnmanagedFileForMissingManaged false --disablePluginRemap false --allowDelete true --allowWrite true --clobber true

      - name: Branch the Solution on the Repository
        uses: microsoft/powerplatform-actions/branch-solution@latest
        with:
          solution-folder: out/${{ secrets.SOLUTION_NAME }}
          solution-target-folder: sln/${{ secrets.SOLUTION_NAME }}
          repo-token: ${{ secrets.SA_GITHUB_TOKEN_PP }}
          allow-empty-commit: true
          branch-name: feature/${{ inputs.issue-key }}
```

Once the solution files are exported from the dev environment, we move it to the testing environment by importing it as an unmanaged solution back to the dev environment, exporting it as a managed solution, uploading to the artifact store and importing that artifact to the next environment i.e. testing. During this workflow, we are getting the following error when the same exported solution is being imported again to the dev environment:

![image](https://github.com/user-attachments/assets/2cbd76ba-2469-4950-bc73-5540c64eb005)

I am providing the failing workflow below for your reference:

```
name: Release Managed Solution
on:
 workflow_call:
jobs:
  convert-to-managed:
    if: github.ref == 'refs/heads/qa'
    runs-on: windows-latest
    environment: 
      name: 'DEV'
    steps:
    - name: Configure Git for long paths
      run: git config --global core.longpaths true
        
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Download/install pac CLI
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: Authentication using pac cli
      run: pac auth create --environment "${{ secrets.ENVIRONMENT_URL }}" --username "${{ secrets.POWERPLATFORM_USERNAME }}" --password "${{ secrets.POWERPLATFORM_PASSWORD }}"

    - name: Pack solution
      run: pac solution pack --zipfile out/${{ secrets.SOLUTION_NAME }}.zip --folder sln/${{ secrets.SOLUTION_NAME }} --packagetype Unmanaged

    - name: Import Unmanaged Solution
      run: pac solution import --environment "${{ secrets.ENVIRONMENT_URL }}" --path out/${{ secrets.SOLUTION_NAME }}.zip --async true --force-overwrite true --publish-changes true

    - name: Export Managed Solution
      run: pac solution export --environment "${{ secrets.ENVIRONMENT_URL }}" --path release/artifact/${{ secrets.SOLUTION_NAME }}.zip --name ${{ secrets.SOLUTION_NAME }} --managed true --async true

    - name: Upload to GitHub artifact Store
      uses: actions/upload-artifact@v4
      with:
        name: managedSolutions
        path: release/artifact/${{ secrets.SOLUTION_NAME }}.zip

  release-to-qa:
    if: github.ref == 'refs/heads/qa'
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    environment: 
      name: 'QA'    
    steps:
    - name: Configure Git for long paths
      run: git config --global core.longpaths true
      
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Fetch solution from GitHub Artifact Store
      uses: actions/download-artifact@v4
      with:
        name: managedSolutions
        path: release/artifact/

    - name: Print the run ID for current run
      run: |
        echo "The current run ID is ${{ github.run_id }}"

    - name: Download/install pac CLI
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: Authentication using pac cli
      run: pac auth create --environment "${{ secrets.ENVIRONMENT_URL }}" --username "${{ secrets.POWERPLATFORM_USERNAME }}" --password "${{ secrets.POWERPLATFORM_PASSWORD }}"

    - name: Import Solution
      run: pac solution import --environment "${{ secrets.ENVIRONMENT_URL }}" --path release/artifact/${{ secrets.SOLUTION_NAME }}.zip --async true --force-overwrite true --publish-changes true --settings-file deployment-settings-qa.json

  release-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    environment: 
      name: 'PROD'    
    steps:
    - name: Configure Git for long paths
      run: git config --global core.longpaths true
      
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Fetch the latest run ID for a specific workflow
      id: fetch-run-id
      uses: actions/github-script@v7
      with:
        script: |
          const workflow_id = ".github/workflows/release.yml";
          const branch = "qa"; 
            
          const response = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflow_id,
            branch: branch,
            status: 'success',
            per_page: 1,
          });

          const runs = response.data.workflow_runs;
            
          if (!runs || runs.length === 0) {
            throw new Error("No workflow runs found");
          }

          const run_id = runs[0].id;
          console.log(`Found run ID: ${run_id}`);

          core.setOutput("run-id", run_id);;

    - name: Fetch artifacts from the workflow run
      id: fetch-artifact
      uses: actions/github-script@v7
      with:
        script: |
          const run_id = ${{ steps.fetch-run-id.outputs['run-id'] }};
            
          const response = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run_id,
          });

          const artifacts = response.data.artifacts;
          if (!artifacts || artifacts.length === 0) {
            throw new Error("No artifacts found for the run");
          }

          const artifact = artifacts.find(a => a.name === "managedSolutions");
          if (!artifact) {
            throw new Error("Artifact 'managedSolutions' not found");
          }

          core.setOutput("artifact-id", artifact.id);

    - name: Download the artifact using its ID
      run: |
        $ARTIFACT_ID = "${{ steps.fetch-artifact.outputs['artifact-id'] }}"
        curl.exe -L -o artifact.zip `
          -H "Authorization: token ${{ secrets.SA_GITHUB_TOKEN_PP }}" `
          -H "Accept: application/vnd.github.v3+json" `
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip"
      shell: powershell
        
    - name: Unzip and use the artifact
      run: Expand-Archive -Path artifact.zip -DestinationPath release/artifact
      shell: powershell

    - name: Download/install pac CLI
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: Authentication using pac cli
      run: pac auth create --environment "${{ secrets.ENVIRONMENT_URL }}" --username "${{ secrets.POWERPLATFORM_USERNAME }}" --password "${{ secrets.POWERPLATFORM_PASSWORD }}"

    - name: Import Solution
      run: pac solution import --environment "${{ secrets.ENVIRONMENT_URL }}" --path release/artifact/${{ secrets.SOLUTION_NAME }}.zip --async true --force-overwrite true --publish-changes true --settings-file deployment-settings-prod.json
```

We tried checking the solution on the Power Platform to look for any name discrepancy, but we didn't find any. We tried troubleshooting this on our own for a long time but had no luck. We even reached out to the Power Platform support team long back, and they are still trying to find the issue. Our deployments are blocked for this particular app/solution due to this issue.

When the solution gets exported manually from the Power Platform, the exported files have no issue and the import of that manually exported solution is successful. Therefore, we feel it could be the issue with the PAC CLI being used within the actions we are using in our workflows. We are really looking forward to you guys for urgent support on this. Please let me know if you require any more details for further investigation. 

Thanks and Regards,
Priyanka
