### DISCUSSION TITLE
How to use output variables of Set Connection Variable task

### DISCUSSION THREAD

**Discussion by nsearle97** [microsoft/powerplatform-build-tools#226] [Q&A] [answered]
Hello,

There doesn't appear to be any documentation on the MS website about the Set Connection Variable task, but I do believe it would be useful for a specific requirement that I am dealing with. 
The problem is, I've put it into a test pipeline and it doesn't appear to output anything at all. Presumably I'm missing something but without any documentation it's very unclear as to what this is.
Would someone be able to elaborate on this please?

Many thanks
Noah

**Comment by devkeydet** [comment, marked as answer]
HI @nsearle97.  I contributed this task.  You can see an example of us using it in our ALM Accelerator here:
https://github.com/microsoft/coe-alm-accelerator-templates/blob/433b3f314f83f57ebcf5c610962c4c5babef61eb/Pipelines/Templates/deploy-Solution.yml#L29

![image](https://user-images.githubusercontent.com/4499296/198677722-6b7431f1-6e50-48cb-9198-47ae50eaa9ae.png)

I'll follow up with the rest of the team on the documentation plans.

**Reply by nsearle97** [reply]
Thank you @devkeydet that's really helpful!

**Comment by devkeydet** [comment]
Until we have better docs, you can review the output variables the task sets here:
https://github.com/microsoft/powerplatform-build-tools/blob/main/src/tasks/set-connection-variables/set-connection-variables-v2/task.json#L24

**Comment by craig-lund** [comment]
This works great! 

For those who don't use yaml, know that the way to access is as follows. 

$(PowerPlatformSetConnectionVariables.BuildTools.TenantId)
$(PowerPlatformSetConnectionVariables.BuildTools.ApplicationId)
$(PowerPlatformSetConnectionVariables.BuildTools.ClientSecret)

Reduced the need to create a Library to access Key Vault values.

**Comment by INC02203** [comment]
Hi team,

I am working on a script where i need to read Tenant Id. So i used PowerPlatformSetConnectionVariables task followed by PowerShell script with inline target script, where i am successfully able to read Tenant Id.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/102131849/a973e154-a7b3-4ac7-9b49-36d27465f3aa)

![image](https://github.com/microsoft/powerplatform-build-tools/assets/102131849/6c2f4163-2aad-409c-9ad9-1d74903f2e5b)

**But, when i try to use same script through file path (same script is copied to file in azure repo). am not able to read Tenant id value.**

![image](https://github.com/microsoft/powerplatform-build-tools/assets/102131849/d1eab40d-1efe-468a-98f9-4b0ec84c83a4)

![image](https://github.com/microsoft/powerplatform-build-tools/assets/102131849/abb5f82c-98ad-48a6-a23e-f269d0e79b16)

![image](https://github.com/microsoft/powerplatform-build-tools/assets/102131849/cc2d686e-345c-4ad6-819e-4d0a08c17231)

Code Snippet: 

`
Write-Host "Hello World"
Write-Host "Tenant Id - $(PowerPlatformSetConnectionVariables.BuildTools.TenantId)"
`

Log:

`
2023-08-22T20:01:02.1961457Z ##[section]Starting: Test
2023-08-22T20:01:02.2088493Z ==============================================================================
2023-08-22T20:01:02.2088695Z Task         : PowerShell
2023-08-22T20:01:02.2088777Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2023-08-22T20:01:02.2088898Z Version      : 2.226.1
2023-08-22T20:01:02.2088995Z Author       : Microsoft Corporation
2023-08-22T20:01:02.2089088Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2023-08-22T20:01:02.2089235Z ==============================================================================
2023-08-22T20:01:03.5951682Z Generating script.
2023-08-22T20:01:03.6128745Z Formatted command: . 'D:\a\r1\a\_User Provisioning\PowerShell\scripts\test.ps1'
2023-08-22T20:01:03.6998738Z ========================== Starting Command Output ===========================
2023-08-22T20:01:03.7296379Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\b5249799-8aef-48cc-bbe9-4ca82a4d378e.ps1'"
2023-08-22T20:01:04.0815114Z Hello World
2023-08-22T20:01:04.3463314Z PowerPlatformSetConnectionVariables.BuildTools.TenantId : The term 
2023-08-22T20:01:04.3463961Z 'PowerPlatformSetConnectionVariables.BuildTools.TenantId' is not recognized as the name of a cmdlet, function, script 
2023-08-22T20:01:04.3464502Z file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
2023-08-22T20:01:04.3467696Z and try again.
2023-08-22T20:01:04.3468749Z At D:\a\r1\a\_User Provisioning\PowerShell\scripts\test.ps1:4 char:27
2023-08-22T20:01:04.3469404Z + ... nant Id - $(PowerPlatformSetConnectionVariables.BuildTools.TenantId)" ...
2023-08-22T20:01:04.3469775Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-08-22T20:01:04.3470167Z     + CategoryInfo          : ObjectNotFound: (PowerPlatformSe...dTools.TenantId:String) [], ParentContainsErrorRecord 
2023-08-22T20:01:04.3470489Z    Exception
2023-08-22T20:01:04.3470804Z     + FullyQualifiedErrorId : CommandNotFoundException
2023-08-22T20:01:04.3471599Z  
2023-08-22T20:01:04.4674118Z ##[error]PowerShell exited with code '1'.
2023-08-22T20:01:04.5094765Z ##[section]Finishing: Test

`

Any help?

Thanks

**Reply by sdgmits** [reply]
I am also facing a similar issue.

**Reply by craig-lund-palm** [reply]
Hi, 

It is a scope issue. Please pass the value to your script rather than calling it inside the script. 

Regards

**Comment by tiagodenoronha** [comment]
Hey, so I've been hitting my head a bit with this.
I created a fairly simple pipeline.

```
pool:
  vmImage: ubuntu-latest

steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    AddToolsToPath: true

- task: PowerPlatformSetConnectionVariables@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'Dev SC'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pac auth create `
        --applicationId "$(BuildTools.ApplicationId)" `
        --clientSecret "$(BuildTools.ClientSecret)" `
        --tenant "$(BuildTools.TenantId)" `
        --environment "$(BuildTools.EnvironmentUrl)"
```
    
I have tried multiple approaches:
Not adding anything like the example
Using PowerPlatformSetConnectionVariables.BuildTools.ApplicationId
Naming the PowerPlatformSetConnectionVariables and using that in the PowerShell

Any thoughts? This seems like a simple error which I'm just close to solving.

**Reply by craig-lund** [reply]
Hi @tiagodenoronha,

I too struggled with the poor documentation and examples on this. 

Tri this:
$(PowerPlatformSetConnectionVariables.BuildTools.TenantId)
$(PowerPlatformSetConnectionVariables.BuildTools.ApplicationId)
$(PowerPlatformSetConnectionVariables.BuildTools.ClientSecret)

**Reply by tiagodenoronha** [reply]
Hey! 
Unfortunately, exactly the same error...
<img width="606" height="180" alt="image" src="https://github.com/user-attachments/assets/10c937e1-56db-45c7-9e50-bc263eaa2642" />

**Reply by tiagodenoronha** [reply]
What's even more strange, is that I can see in the logs that the Set Connection step creates the BuildTools variables:
<img width="819" height="148" alt="image" src="https://github.com/user-attachments/assets/788506c5-b927-498a-9895-c0e0f522c7ea" />
They all have isOutput=false, which shouldn't matter but...

**Reply by tiagodenoronha** [reply]
Ok finally figured it out! Leaving this here if anyone else has the same issue.

Here is an example pipeline which works.

```
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    AddToolsToPath: true

- task: PowerPlatformSetConnectionVariables@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'Dev SC'

- pwsh: |
      pac auth create `
        --applicationId "$(PowerPlatformSetConnectionVariables.BuildTools.ApplicationId)" `
        --clientSecret "$(PowerPlatformSetConnectionVariables.BuildTools.ClientSecret)" `
        --tenant "$(PowerPlatformSetConnectionVariables.BuildTools.TenantId)" `
        --environment "$(BuildTools.EnvironmentUrl)"
```

Notice that the EnvironmentUrl property **does not have the PowerPlatformSetConnectionVariables** before, which was the cause of the issue.
Besides those properties, you can also use **PowerPlatformSetConnectionVariables.BuildTools.DataverseConnectionString** if needed.

Thanks for the help @craig-lund!
