### DISCUSSION TITLE
Acessing Power Platform CLI - POWERPLATFORMTOOLS_PACCLIPATH

### DISCUSSION THREAD

**Discussion by fowl2** [microsoft/powerplatform-build-tools#292] [Q&A] [answered]
The tool installer task [seems to](https://github.com/microsoft/powerplatform-build-tools/blob/3a7c95c1aa300e8388ef2d4bda722cdb14fa413c/src/host/CliLocator.ts) make the Power Platform CLI available under these paths:

On Linux: `$(POWERPLATFORMTOOLS_PACCLIPATH)/pac_linux/tools/pac`
On Windows: `$(POWERPLATFORMTOOLS_PACCLIPATH)/pac/tools/pac.exe`

This isn't the most convenient, but very very useful!

Is it possible to have the tool installer (possibly optionally) add this directory to `PATH`? This way we could just use `pac` in our scripts.

I'd also suggest a "Power Platform CLI Task" for easier access to functionality that doesn't yet have a dedicated task.

**Comment by BetimBeja** [comment, marked as answer]
@fowl2 (and 👀 @rpothin)
In Azure DevOps you can use the [Prepend Path](https://learn.microsoft.com/azure/devops/pipelines/scripts/logging-commands?WT.mc_id=DX-MVP-5004767#prependpath-prepend-a-path-to-the--path-environment-variable) logging action. Examples:

- windows agent:
```yml
- pwsh: |
    $pac = Join-Path $env:POWERPLATFORMTOOLS_PACCLIPATH pac tools
    echo "##vso[task.prependpath]$pac"
  displayName: 'Add PAC to Path' 
```

- linux agent:
```yml
- pwsh: |
    $pac = Join-Path $env:POWERPLATFORMTOOLS_PACCLIPATH pac_linux tools
    echo "##vso[task.prependpath]$pac"
  displayName: 'Add PAC to Path' 
``` 

It will add the directory to `PATH` for all the subsequent tasks, and you can easily use pac in a script.

I haven't tested GitHub Actions yet. But the same should be achieved by adding to [GITHUB_PATH](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?tool=powershell#adding-a-system-path) environment variable.

`UPDATE 2023-12-31`:
In GitHub Actions you can use the following step (Windows and Linux) to Add a System Path:

```yml
- name: Add pac to PATH
  shell: pwsh
  run: |
    $pac = (Get-Item "$env:POWERPLATFORMTOOLS_PACPATH").Directory.FullName;
    "$pac" | Out-File -FilePath $env:GITHUB_PATH -Append

```
