### DISCUSSION TITLE
Power Platform Import Solution Error: The reason given was: An unexpected error occurred.

### DISCUSSION THREAD

**Discussion by tonocode** [microsoft/powerplatform-build-tools#739] [Q&A] [answered]
I am attempting to import my solution from DEV to TEST and then to PROD environment.

I am using a multi-staged YAML approach and I have used a template.yml for the release stages to TEST and PROD. The pipeline has successfully deployed changes to the TEST environment. However, the final stage to PROD fails during "Processing asynchronous operation..." with the error message  "The reason given was: An unexpected error occurred."

I ran the pipeline again (new) and get another error message "The reason given was: ImportAsHolding failed with exception :Solution manifest import: FAILURE: Cannot create a holding solution for missing base ALM_Demo."

This is my code in the deployment-template.yml for the relevant task:
``` 
- task: PowerPlatformImportSolution@2  
   inputs:
         authenticationType: 'PowerPlatformSPN'
         PowerPlatformSPN: '${{parameters.powerplatform_service_connection}}'
         SolutionInputFile: '$(Agent.BuildDirectory)/drop/${{parameters.solution_name}}_managed.zip'
         UseDeploymentSettingsFile: true
         DeploymentSettingsFile: '$(Agent.BuildDirectory)/drop/${{parameters.deployment_settings_file_name}}'
         AsyncOperation: true
         MaxAsyncWaitTime: '60'
```

UPDATE:
I manually imported the managed solution into the PROD environment first and re-ran the failed pipeline which then worked. Does the solution need to exist before using the import solution?
