### DISCUSSION TITLE
How can add the security group id in the creation of the env using the step in Azure DevOps?

### DISCUSSION THREAD

**Discussion by javiertafurpino** [microsoft/powerplatform-build-tools#830] [Q&A]
How can add the security group id in the creation of the env using the step in Azure DevOps? 

![image](https://github.com/microsoft/powerplatform-build-tools/assets/7656046/c534646f-a021-478b-afc5-28e0b4b1573a)

I can use pac cli https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin#--security-group-id--sgid.

But Im not sure that is possible in the build tools for DevOps.

**Comment by devkeydet** [comment]
Doesn't look like we expose it in the task, but we should.  For now, you can always drop to direct pac cli calls.  There are a number of examples floating around, but see below for another.  We are working on making it easier to call pac from a script task in a pipeline directly.  For now, you have to do a bit of work to set it up.  Once we make this more "easy button", I'll update the docs to make it more obvious that you can do this.  I'll also look at submitting a PR that exposes the `--security-group-id` parameter available to `pac admin create`.

```
trigger: none

pool:
  vmImage: windows-latest

steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
- task: PowerPlatformSetConnectionVariables@2
  name: connectionVariables
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'pipelines-spn'
- task: PowerShell@2
  name: setPacPath
  inputs:
    targetType: 'inline'
    script: |
      $pacPath = $env:POWERPLATFORMTOOLS_PACCLIPATH + "\pac\tools"
      $fullPath = $env:PATH + ";" + $pacPath
      Write-Host "##vso[task.setvariable variable=PATH;]${env:PATH};$fullPath"
    pwsh: true
- task: PowerShell@2
  name: authenticatePac
  inputs:
    targetType: 'inline'
    script: |
      $clientId = "$(connectionVariables.BuildTools.ApplicationId)"
      $clientSecret = "$(connectionVariables.BuildTools.ClientSecret)"
      $tenantId = "$(connectionVariables.BuildTools.TenantId)"
      $url = "$(BuildTools.EnvironmentUrl)"
      pac auth create --name devops-temp --tenant $tenantId --applicationId $clientId --clientSecret $clientSecret --environment $url
    pwsh: true
- task: PowerShell@2
  name: pacEnvWho
  inputs:
    targetType: 'inline'
    script: |
      pac env who
    pwsh: true
```
