### DISCUSSION TITLE
Workload Identity Federation Preview

### DISCUSSION THREAD

**Discussion by tehcrashxor** [microsoft/powerplatform-build-tools#884] [Announcements]
With the release of Power Platform Build Tools [v2.0.69](https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.69) and its underlying PAC [v1.32.6](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.32.6#releasenotes-body-tab), Service Principals can now authenticate with OpenID Connect (OIDC), federated with Azure DevOps . This enables the removal of Service Connections with Client Secrets.

To use this new option:
1. Create a new Power Platform Service Connection, select "Workload Identity federation (preview)", and supply your Dataverse Organization URL, Service Principal ID (App ID), and Tenant ID
2. Configure the App Registration in the Azure Portal with federated credentials to your Azure DevOps org

### Add Federated Credentials to the App Registration

1. Go to **App registrations** in the Azure Portal and open the app associated with your Service Principal
2. Select **Certificates and Secrets** in the Manage panel
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/e6560eee-e5ef-458c-8fa6-28a13c1c2c12)
3. In the **Federated credentials** tab, select **Add credential**
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/853ee19b-6b0a-4a18-a667-d530eefe6748)
4. Select the credential scenario **Other issuer**, and set the **Issuer** and **Subject identifier** fields for your Azure DevOps Service Connection
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/7aa863a2-994e-425d-ac5d-58451be70897)
  * The **Issuer** field must be `https://vstoken.dev.azure.com/[AzureDevOpsOrganizationID]`
  * The **Subject identifier** field must be in the format `sc://[AzureDevOpsOrganizationName]/[AzureDevOpsProjectName]/[AzureDevOpsServiceConnectionName]`
  * If these values are missing or misconfigured, running any of the Power Platform Build Tools tasks with a misconfigured Workload identity will output the expected values to the Pipeline logs.

**Comment by richardcarrigan** [comment]
This is HUGE and works perfectly for tasks which invoke the service connection directly.

For one of my use cases, however, I'm running `pac auth create --url $url --name $envName --applicationId $applicationId --tenant $tenant --azureDevOpsFederated` inside of a Bash script file executed by the ADO pipeline, but I'm getting the error `Error: Execution environment is either not an Azure DevOps Pipeline or is not configued correctly. Required PAC_ADO_ID_TOKEN_REQUEST_TOKEN or PAC_ADO_ID_TOKEN_REQUEST_URL environment variables are missing`. When I try to inject these into the Bash execution environment using the `env` param for the `Bash@3` task, I then get the error `Error: Request to Azure DevOps Token Federation endpoint failed.`

```yaml
# azure-pipelines.yml

- task: Bash@3
  displayName: Deploy solutions
  inputs:
    filePath: 'deploySolutions.sh'
  env:
    url: $(PP_ENV_URL)
    envName: $(PP_ENV_NAME)
    applicationId: $(CLIENT_ID)
    tenant: $(TENANT)
    PAC_ADO_ID_TOKEN_REQUEST_TOKEN: $(PAC_ADO_ID_TOKEN_REQUEST_TOKEN)
    PAC_ADO_ID_TOKEN_REQUEST_URL: $(PAC_ADO_ID_TOKEN_REQUEST_URL)
```

```bash
# deploySolutions.sh

pac auth create --url $url --name $envName --applicationId $applicationId --tenant $tenant --azureDevOpsFederated
```

What am I missing?

**Reply by devkeydet** [reply]
I think @tehcrashxor explained to me that the way Azure DevOps works with all this, you need to call a task that uses the SPN first.  Can you try to call the whoami task first, then try again?

**Reply by tehcrashxor** [reply]
The error message `Error: Request to Azure DevOps Token Federation endpoint failed` indicates that PAC's request to the ADO [API to get the OIDC token](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/oidctoken/create?view=azure-devops-rest-7.2) got a non-success response.  ADO auth APIs usually don't return much in the way of useful information for determining what went wrong, so we end up with guesswork trying to figure out what needs to be updated.

As @devkeydet said, the issue might be that you haven't executed a Task within that Job using the needed Service Connection.   ADO does not load the Service Connections into the pipeline until they're used in a task, so it could be that just doing a WhoAmI task above might resolve the issue.

Perhaps the value you are setting for the Token is wrong?
The tasks set the `PAC_ADO_ID_TOKEN_REQUEST_TOKEN` for consumption in PAC [here in getCredentials.ts](https://github.com/microsoft/powerplatform-build-tools/blob/main/src/params/auth/getCredentials.ts#L36), which you can also do by setting it to the `System.AccessToken` such as: 
```yaml
- task: Bash@3
  # ....
  env:
    PAC_ADO_ID_TOKEN_REQUEST_TOKEN: $(System.AccessToken)
```

Perhaps the value you are setting for the Request URL is wrong?
The request URL defined in the [API here](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/oidctoken/create?view=azure-devops-rest-7.2) requires values dependent on the current Job execution, and thus change every time that Job is executed.  Our code here in [getCredential.ts](https://github.com/microsoft/powerplatform-build-tools/blob/main/src/params/auth/getCredentials.ts#L62-L75) is able to set _most_ of the fields in the Request URL from Environment Variables set by the pipeline, but the Service Connection ID is not set in a convenient way to grab within a script.  That ID however can be found by opening up the Service Connection in the UI, and taking the `resourceId` GUID that appears in the address bar.

**Reply by richardcarrigan** [reply]
Thank you @devkeydet and @tehcrashxor for the advice. Unfortunately, even after adding the `PowerPlatformToolInstaller@2` and `PowerPlatformWhoAmi@2` tasks into the pipeline YAML and using `System.AccessToken` to populate the `PAC_ADO_ID_TOKEN_REQUEST_TOKEN` env var, I'm still getting the same error.

When I `echo` each of these variables in Bash, here's what I get:

```bash
PAC_ADO_ID_TOKEN_REQUEST_TOKEN: ***
PAC_ADO_ID_TOKEN_REQUEST_URL: $(PAC_ADO_ID_TOKEN_REQUEST_URL)
```

This tells me that the token is probably being set correctly now, since it's being obfuscated, and that the URL is definitely not being set. So, with the `resourceId` in hand, I manually built the URL similar to how it was done in `getCredential.ts` and I can confirm that this solves my issue.

Thank you so much!

**Reply by devkeydet** [reply]
Thanks @richardcarrigan!  Here is a working example for others to follow / adapt.

```yaml
trigger: none
pool:
  vmImage: ubuntu-latest
variables:
  BuildTools.EnvironmentUrl: "YOUR-URL"
steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
    AddToolsToPath: true
- task: PowerPlatformWhoAmi@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'YOU-SVC-CONN-NAME'
- task: PowerShell@2
  env:
    PAC_ADO_ID_TOKEN_REQUEST_TOKEN: $(System.AccessToken)
  inputs:
    targetType: 'inline'
    script: |
      $uri = "$(System.CollectionUri)"
      $projectId = "$(System.TeamProjectId)"
      $hub = "$(System.HostType)"
      $planId = "$(System.PlanId)"
      $jobId = "$(System.JobId)"
      $serviceConnectionId = "YOUR-SVC-CONN-ID"
      $oidcApiVersion = "7.2-preview.1"
      $env:PAC_ADO_ID_TOKEN_REQUEST_URL = "$uri$projectId/_apis/distributedtask/hubs/$hub/plans/$planId/jobs/$jobId/oidctoken?serviceConnectionId=$serviceConnectionId&api-version=$oidcApiVersion"
      $environment = "$(BuildTools.EnvironmentUrl)"

      pac auth create --name devops-temp --environment $environment --azureDevOpsFederated --tenant YOUR-TENANT-ID --applicationId YOUR-APP-ID
    pwsh: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pac env who
    pwsh: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pac solution list
    pwsh: true
```

**Reply by richardcarrigan** [reply]
FWIW, here's the bash version that I went with:
```yaml
# azure-pipelines.yml

trigger: none
pool:
  vmImage: windows-latest
stages:
  - stage: UAT_Deploy
    jobs:
      - deployment: DeployToUAT
        displayName: Deploy Power Platform solutions to UAT
        environment: 'uat' # creates an environment if it doesn't exist
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: NuGetAuthenticate@1
                  inputs:
                    forceReinstallCredentialProvider: false
                - task: CmdLine@2
                  displayName: Install Power Platform CLI
                  inputs:
                    script: |
                      dotnet tool install --global Microsoft.PowerApps.CLI.Tool
                - task: PowerPlatformToolInstaller@2
                  inputs:
                    DefaultVersion: true
                - task: PowerPlatformWhoAmi@2
                  inputs:
                    authenticationType: 'PowerPlatformSPN'
                    PowerPlatformSPN: 'uatserviceconnection'
                    Environment: '$(UAT_URL)'
                - task: Bash@3
                  displayName: Deploy solutions
                  inputs:
                    filePath: 'deploySolutions.sh'
                  env:
                    url: $(UAT_URL)
                    envName: $(UAT_ENV_NAME)
                    applicationId: $(UAT_CLIENT_ID)
                    tenant: $(TENANT)
                    PAC_ADO_ID_TOKEN_REQUEST_TOKEN: $(System.AccessToken)
                    PAC_ADO_ID_TOKEN_REQUEST_URL: '$(System.CollectionUri)$(System.TeamProjectId)/_apis/distributedtask/hubs/$(System.HostType)/plans/$(System.PlanId)/jobs/$(System.JobId)/oidctoken?serviceConnectionId=$(SERVICE_CONNECTION_ID)&api-version=7.2-preview.1'
```
```bash
# deploySolutions.sh

pac auth create --url $url --name $envName --applicationId $applicationId --tenant $tenant --azureDevOpsFederated
```

**Reply by tehcrashxor** [reply]
Looks like ADO had a recent release where they are now setting the `System.OidcRequestUri`.  It still needs the `api-version` and `serviceCeonnectionId` parameters provided in the query string, but reduces the steps needed to construct the url.

**Reply by TalviArt** [reply]
Is there a limitation which Power Platform CLI Commands/Command Groups can be used in pipeline task after authenticating with temporary auth profile? I'm able to run for example "pac env who" and "pac solution list", but when trying to run "pac application list" I get an error: 

"Error: Execution environment is either not an Azure DevOps Pipeline or is not configued correctly. Required PAC_ADO_ID_TOKEN_REQUEST_TOKEN or PAC_ADO_ID_TOKEN_REQUEST_URL environment variables are missing" 

I wonder why the other pac commands works but "pac application list" throws an error.

**Reply by petrochuk** [reply]
Each command/command group might call different APIs which might need separate permissions. For example `env list` calls Global Discovery Service, in your case `pac application list` calls Power Platform API [Applications - Get Environment Application Package](https://learn.microsoft.com/en-us/rest/api/power-platform/appmanagement/applications/get-environment-application-package)

**Reply by TalviArt** [reply]
Thanks for the reply. 

The issue seemed to be  `pac application list` not able to find PAC env variables when executed in separate PowerShell@2 tasks after the authentication profile was created. Running the `pac application list` in the same PowerShell@2 task with `pac auth create` worked.

**Reply by mathiasbl** [reply]
> Thanks @richardcarrigan! Here is a working example for others to follow / adapt.
> 
> ```yaml
> trigger: none
> pool:
>   vmImage: ubuntu-latest
> variables:
>   BuildTools.EnvironmentUrl: "YOUR-URL"
> steps:
> - task: PowerPlatformToolInstaller@2
>   inputs:
>     DefaultVersion: true
>     AddToolsToPath: true
> - task: PowerPlatformWhoAmi@2
>   inputs:
>     authenticationType: 'PowerPlatformSPN'
>     PowerPlatformSPN: 'YOU-SVC-CONN-NAME'
> - task: PowerShell@2
>   env:
>     PAC_ADO_ID_TOKEN_REQUEST_TOKEN: $(System.AccessToken)
>   inputs:
>     targetType: 'inline'
>     script: |
>       $uri = "$(System.CollectionUri)"
>       $projectId = "$(System.TeamProjectId)"
>       $hub = "$(System.HostType)"
>       $planId = "$(System.PlanId)"
>       $jobId = "$(System.JobId)"
>       $serviceConnectionId = "YOUR-SVC-CONN-ID"
>       $oidcApiVersion = "7.2-preview.1"
>       $env:PAC_ADO_ID_TOKEN_REQUEST_URL = "$uri$projectId/_apis/distributedtask/hubs/$hub/plans/$planId/jobs/$jobId/oidctoken?serviceConnectionId=$serviceConnectionId&api-version=$oidcApiVersion"
>       $environment = "$(BuildTools.EnvironmentUrl)"
> 
>       pac auth create --name devops-temp --environment $environment --azureDevOpsFederated --tenant YOUR-TENANT-ID --applicationId YOUR-APP-ID
>     pwsh: true
> - task: PowerShell@2
>   inputs:
>     targetType: 'inline'
>     script: |
>       pac env who
>     pwsh: true
> - task: PowerShell@2
>   inputs:
>     targetType: 'inline'
>     script: |
>       pac solution list
>     pwsh: true
> ```

@devkeydet 
This example stops working as soon as you remove the Who Am I action. 
The first powershell actually does nothing because the whoami action already authenticated so it just reuses that connection.

I cannot get it to work using the oidcRequestUri even with a plain example like mentioned here: https://learn.microsoft.com/en-us/azure/devops/release-notes/2024/sprint-240-update#azure-cli

**Reply by geekzter** [reply]
You will not be able to get an OIDC token for a service connection that is not used in a task in the pipeline job you're requesting a token for.

**Comment by Dohsan** [comment]
We have started to move over to using the Workload Identity federation.

Noticed an issue using the `PowerPlatformSetConnectionVariables@2` task

```yaml
# yaml
            - task: PowerPlatformSetConnectionVariables@2
              displayName: 'Get Service Principal Credentials'
              name: SP_credentials
              inputs:
                authenticationType: 'PowerPlatformSPN'
                PowerPlatformSPN: ${{ parameters.SPN }}             
```

`##[warning]LIB_ResourceFile does not exist`
`##[warning]Resource file haven't been set, can't find loc string for key: LIB_EndpointAuthNotExist`
`##[error]Error: LIB_EndpointAuthNotExist`

Not something we've seen before and replicated it on both pipelines where we'd updated the Service Connection to use WIF

Other tasks using the SPN worked with no issue.

**Reply by tehcrashxor** [reply]
Hmm.
Looks like that [code path](https://github.com/microsoft/powerplatform-build-tools/blob/main/src/tasks/set-connection-variables/set-connection-variables-v2/index.ts#L32-L46) only expects SPNs to be using Client Secrets, and would break in the same way for Managed Identities.

@devkeydet , there isn't a Dataverse Connection String that works for Managed Identities or Federated flows, but we could still set the other values.  Thoughts?  Might tie into discussion #906

**Reply by devkeydet** [reply]
I wouldn't expect to be able to use PowerPlatformSetConnectionVariables with workload identify federation.  The variables set when using SPN or Username/Password are not there in the service connection.  I do not think there is a connection string format to use workload federated identity.  @MattB-msft might have some thoughts on what it would take to get clients that use the connection string format to use the token created via workload identity federation.

**Comment by seanmcne** [comment]
Dropping this here, for anyone else looking for how to find the "AzureDevOpsOrganizationID" value (courtesy of @tehcrashxor) https://github.com/microsoft/powerplatform-build-tools/issues/916#issuecomment-2166965377 

> With the release of Power Platform Build Tools [v2.0.69](https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.69) and its underlying PAC [v1.32.6](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.32.6#releasenotes-body-tab), Service Principals can now authenticate with OpenID Connect (OIDC), federated with Azure DevOps . This enables the removal of Service Connections with Client Secrets.
> 
> To use this new option:
> 
> 1. Create a new Power Platform Service Connection, select "Workload Identity federation (preview)", and supply your Dataverse Organization URL, Service Principal ID (App ID), and Tenant ID
> 2. Configure the App Registration in the Azure Portal with federated credentials to your Azure DevOps org
> 
> ### Add Federated Credentials to the App Registration
> 1. Go to **App registrations** in the Azure Portal and open the app associated with your Service Principal
> 2. Select **Certificates and Secrets** in the Manage panel
>   
> 3. In the **Federated credentials** tab, select **Add credential**
>   
> 4. Select the credential scenario **Other issuer**, and set the **Issuer** and **Subject identifier** fields for your Azure DevOps Service Connection
>   
> 
> * The **Issuer** field must be `https://vstoken.dev.azure.com/[AzureDevOpsOrganizationID]`
> * The **Subject identifier** field must be in the format `sc://[AzureDevOpsOrganizationName]/[AzureDevOpsProjectName]/[AzureDevOpsServiceConnectionName]`
> * If these values are missing or misconfigured, running any of the Power Platform Build Tools tasks with a misconfigured Workload identity will output the expected values to the Pipeline logs.

**Reply by h-karthik12** [reply]
$(System.CollectionId) variable also fetches the  OrganizatonID

**Comment by Hjaf** [comment]
How federated credentials can be utilized with GitHub Actions was not very clear from the documentation, but it seems to be pretty straight forward with the right setup. I'm just putting this here in case someone else struggle to understand the documentation for this like I did; eventually finding themselves at this discussion.
I'm assuming the  credentials in the app registration (GitHub) is set up correctly for the repository where the action is triggered.

The permissions section of the GH-action needs to be set for the id-token to be updated:
```yaml
permissions:
  id-token: write
```
> See [GitHub docs for more info](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings)

Omitting the client-secret from the steps, is all that is needed for federated authentication to be used:
> This is detected automatically from what i understand of [this PR](https://github.com/microsoft/powerplatform-actions/pull/540/files#diff-fcc8fab8c663aa8c54d26b2bf7f1988368bb1c9fa156e45c50e0b04b2614485cR32)
```yaml
    - name: Install PAC
      uses: microsoft/powerplatform-actions/actions-install@v1
      with:
        add-tools-to-path: true
        
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.DATAVERSE_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        tenant-id: ${{ env.TENANT_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET }} # <-- Removing this seems to be sufficient. 
```
