### DISCUSSION TITLE
Value of task wrappers over pac cli vs calling pac cli directly?

### DISCUSSION THREAD

**Discussion by devkeydet** [microsoft/powerplatform-build-tools#906] [Ideas]
One of the things we've recently introduced is making it easier to call pac cli directly in script tasks.  Here's a trivial example.

```yaml
trigger: none
pool:
  vmImage: ubuntu-latest
steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
    AddToolsToPath: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pac
    pwsh: true
```

For those who may not be aware, the Power Platform Build Tools tasks are almost exclusively convenience wrappers over `pac`, enabling you to execute `pac` capability using the yaml declarative syntax.  We respect that there are strong opinions on the benefits of tasks vs doing the same thing with the `pac` directly.  Some people prefer doing most of their pipeline work in script tasks and cli's.  Some want the convenience of the tasks.  One of the reasons we introduced `AddToolsToPath` is because there is effort to create each task or enhance tasks as we add capabilities to `pac`.  We can't always get everything in `pac` exposed as a task in a given release and sometimes, due to other priorities, many things lag.  Furthermore, it's debatable whether everything that `pac` offers should be a task in the first place.  The "escape hatch" is "drop to pac in a script task".  Personally, I have used this approach myself ever since the tasks were rewritten to be `pac` wrappers (and before joining the team).  Increasingly, because of my own personal preference of using script tasks, I find myself using the tasks less and less, and calling pac directly in my pipelines more and more.

All of this leads to a potentially controversial, thought provoking, and opinionated discussion...

**If we continue down this trend to make it "easy button" to use `pac` in script tasks, including making the auth setup more seamless, what's the value of task wrappers over `pac` vs calling `pac` directly to you?**  

Let the discussion begin...

**Comment by tehcrashxor** [comment]
As with many things, the differences come down to the tradeoffs between these different methods.  One such tradeoff is in Service Connections:

### Service Connections

ADO [Service Connections](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml) provide a mechanism to share and control access to credentials across multiple pipelines.  To take advantage of those, the task in question needs to be built to support them, so they cannot be sent to tasks such as the PowerShell script task.

As an alternative to using Service Connections, some auth information such as the username + password flow and the Service Principal via App ID + Tenant ID + Client Secret flow could be fairly easily handled with pipeline variables (or variable groups to share between multiple pipelines).  This does however move the responsibility to mark the password or client secret as a _secret_ onto the user, and not doing so could result in the credential leaking in the task logs.  Using our Service Connections will always mark those values as secret, and thus ADO will mask those values in the logs without the user needing to do so themselves.

The bigger disadvantage to moving to running PAC directly here is in the [Workload Identity Federation](https://github.com/microsoft/powerplatform-build-tools/discussions/884) type.  The ADO implementation of WIF sets the federated trust relationship between the Entra ID App and an ADO Service Connection.  While there are workarounds to using that WIF Service Connection in that same linked discussion ([direct link to the relevant post here](https://github.com/microsoft/powerplatform-build-tools/discussions/884#discussioncomment-9618506)), it does take some work to use that federated connection with a direct command line call, and is more of a hybrid approach.

**Reply by devkeydet** [reply]
But if we fixed those things?

**Reply by devkeydet** [reply]
There are already ways to address some of what you point out, albeit still with too much burden on the pipeline author.  There is opportunity to make both of the scenarios you point out more seamless.  Here are two examples of what you can do today.  Imagine these two scenarios "just work" without having to do the setup below.

Workload Identity Federation, followed by multiple calls to `pac` in subsequent script tasks
```yaml
trigger: none
pool:
  vmImage: ubuntu-latest
variables:
  BuildTools.EnvironmentUrl: "YOUR-URL"
steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
    AddToolsToPath: true
- task: PowerPlatformWhoAmi@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'YOU-SVC-CONN-NAME'
- task: PowerShell@2
  env:
    PAC_ADO_ID_TOKEN_REQUEST_TOKEN: $(System.AccessToken)
  inputs:
    targetType: 'inline'
    script: |
      $uri = "$(System.CollectionUri)"
      $projectId = "$(System.TeamProjectId)"
      $hub = "$(System.HostType)"
      $planId = "$(System.PlanId)"
      $jobId = "$(System.JobId)"
      $serviceConnectionId = "YOUR-SVC-CONN-ID"
      $oidcApiVersion = "7.2-preview.1"
      $env:PAC_ADO_ID_TOKEN_REQUEST_URL = "$uri$projectId/_apis/distributedtask/hubs/$hub/plans/$planId/jobs/$jobId/oidctoken?serviceConnectionId=$serviceConnectionId&api-version=$oidcApiVersion"
      $environment = "$(BuildTools.EnvironmentUrl)"

      pac auth create --name devops-temp --environment $environment --azureDevOpsFederated --tenant YOUR-TENANT-ID --applicationId YOUR-APP-ID
    pwsh: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pac env who
    pwsh: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pac solution list
    pwsh: true
```

Using Service Connection with credentials and SetConnectionVariables
```yaml
trigger: none
pool:
  vmImage: windows-latest
steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
    AddToolsToPath: true
- task: PowerPlatformSetConnectionVariables@2
  name: connectionVariables
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'pipelines-spn'
- task: PowerShell@2
  name: authenticatePac
  inputs:
    targetType: 'inline'
    script: |
      $clientId = "$(connectionVariables.BuildTools.ApplicationId)"
      $clientSecret = "$(connectionVariables.BuildTools.ClientSecret)"
      $tenantId = "$(connectionVariables.BuildTools.TenantId)"
      $url = "$(BuildTools.EnvironmentUrl)"
      pac auth create --name devops-temp --tenant $tenantId --applicationId $clientId --clientSecret $clientSecret --environment $url
    pwsh: true
- task: PowerShell@2
  name: pacEnvWho
  inputs:
    targetType: 'inline'
    script: |
      pac env who
    pwsh: true
- task: PowerShell@2
  name: pacSolutionList
  inputs:
    targetType: 'inline'
    script: |
      pac solution list
    pwsh: true
```

Imagine a world where in both the examples above, we had a task that did all the extra work, including wiring up `pac auth`  so all you had to do was something like...
```yaml
trigger: none
pool:
  vmImage: ubuntu-latest
steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
    AddToolsToPath: true
- task: PowerPlatformInitCLI@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'pipelines-spn'
- task: PowerShell@2
  name: pacEnvWho
  inputs:
    targetType: 'inline'
    script: |
      pac env who
    pwsh: true
- task: PowerShell@2
  name: pacSolutionList
  inputs:
    targetType: 'inline'
    script: |
      pac solution list
    pwsh: true
```

We could even do something like
```yaml
trigger: none
pool:
  vmImage: windows-latest
steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
    AddToolsToPath: true
- task: PowerPlatformCLI@2
  name: pacEnvWho
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'pipelines-spn'
    targetType: 'inline'
    script: |
      pac env who
    pwsh: true
- task: PowerPlatformCLI@2
  name: pacSolutionList
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'pipelines-spn'
    targetType: 'inline'
    script: |
      pac solution list
    pwsh: true
```
My original goal of this discussion is less about how we can make using the CLI directly a smoother experience.  We can.  We have thoughts here and can explore more. What I was really intending to get feedback on is whether people would be ok with dropping to `pac` if we made it easier or would there still be strong opinion that people expect a task for everything pac does.  I suspect there are lots of other things we can do to simplify.  But this is a pattern we've seen in some other tasks.  Specifically, there are examples of tasks that are just tasks to bootstrap using a specific CLI.
