### ISSUE TITLE
Can't use PowerPlatformSetConnectionVariables to get information from Multiple Service Connections

### ISSUE THREAD

**Issue by mattp65** [microsoft/powerplatform-build-tools#1057]
Using the following tasks:
```
    - task: PowerPlatformSetConnectionVariables@2
      name: devConnInfo
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: ${{parameters.devServiceConnection}}
      displayName: 'Get Dev Connection information'
    - task: PowerPlatformSetConnectionVariables@2
      name: buildConnInfo
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: ${{parameters.buildServiceConnection}}
      displayName: 'Get Build Connection information'

```
End result is both sets of connection values reference later point to the first SPN. In reviewing the step output, it seems to be taking current value of $(BuildTools.EnvironmentUrl) and uses that instead of the the SPN.

In playing with the "settings" editor, it appears that this is defaulting a parm value of "Environment: '$(BuildTools.EnvironmentUrl)'" even though that isn't being provided.

Explicitly setting:
```
    - task: PowerPlatformSetConnectionVariables@2
      name: buildConnInfo
      inputs:
        authenticationType: 'PowerPlatformSPN'
        Environment: ''
        PowerPlatformSPN: ${{parameters.buildServiceConnection}}
      displayName: 'Get Build Connection information'

```
on the second does not seem to override the default.

However, placing a 'bad' value in there like this:
```
    - task: PowerPlatformSetConnectionVariables@2
      name: buildConnInfo
      inputs:
        authenticationType: 'PowerPlatformSPN'
        Environment: '$(bad.EnvironmentUrl)'
        PowerPlatformSPN: ${{parameters.buildServiceConnection}}
      displayName: 'Get Build Connection information'

```
seems to work.

The doc around using this to return info on the SPN is not correct either as it does not include direction on using the task name to qualify the returned values.
