### ISSUE TITLE
Issue with Process CanvasApps in Power Platform Unpack Solution

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/powerplatform-build-tools#135]
Hey All,
I've run across an interesting issue with the Process CanvasApps flag in the new Unpack Solution command. What I've noticed, and been able to reproduce in a generic pipeline, is that while the first time you unpack a solution the source files are created and can be committed to source control, the second time the unpack runs and commits the unpacked canvas app is deleted. The following YAML is what I'm using to test. The result is you can see the unpacked Canvas App in the Initial Commit and that it's deleted in the Second Commit. Let me know if I can provide additional information.

```
pool:
  name: Azure Pipelines
steps:
- powershell: |
   git config user.email "user.onmicrosoft.com"
   git config user.name "User Name"
   git checkout origin/main --track
   git checkout -b 'test' 'refs/heads/main'
   
  displayName: 'PowerShell Script'

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@0
  displayName: 'Power Platform Tool Installer '

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@0
  displayName: 'Power Platform Export Solution Unmanaged'
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: 'https://***.crm.dynamics.com/'
    SolutionName: ALMAcceleratorSampleSolution
    SolutionOutputFile: 'ALMAcceleratorSampleSolution_unmanaged.zip'

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@0
  displayName: 'Power Platform Export Solution Managed'
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: 'https://***.crm.dynamics.com/'
    SolutionName: ALMAcceleratorSampleSolution
    SolutionOutputFile: 'ALMAcceleratorSampleSolution_managed.zip'

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.unpack-solution.PowerPlatformUnpackSolution@0
  displayName: 'Power Platform Unpack Solution '
  inputs:
    SolutionInputFile: 'ALMAcceleratorSampleSolution_unmanaged.zip'
    SolutionTargetFolder: 'ALMAcceleratorSampleSolution_unpacked'
    ProcessCanvasApps: true

- powershell: |
   Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
   git add --all
   git commit -m "Initial Commit"
   git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push origin 'test'
  displayName: 'PowerShell Script'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.unpack-solution.PowerPlatformUnpackSolution@0
  displayName: 'Power Platform Unpack Solution 2'
  inputs:
    SolutionInputFile: 'ALMAcceleratorSampleSolution_unmanaged.zip'
    SolutionTargetFolder: 'ALMAcceleratorSampleSolution_unpacked'
    ProcessCanvasApps: true

- powershell: |
   git add --all
   git commit -m "Second Commit"
   git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push origin 'test'
  displayName: 'PowerShell Script 2'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

```
