### ISSUE TITLE
Unpack Solution step cannot handle both type at the same time

### ISSUE THREAD

**Issue by lar-mar** [microsoft/powerplatform-build-tools#249]
Hi,
the build task for exporting a solution automatically attaches a "_managed" suffix if exported solution is managed.

When I use the same pattern for unpacking solutions and select type = both the steps is not able to identify the unmanaged and managed solution zip file without the full name and attached ".zip".

**Comment by paulbreuler** [comment]
Can you elaborate on how your setup looks when unpacking solution with type == both? 

The managed and unmanaged solution need to be in the same directory, for example.

myDir ->

- someSolution.zip
- someSolution_managed.zip

With this setup the package tooling will unpack the solutions correctly as an aggregate containing unmanaged and managed components files. The _managed suffix is a requirement.

**Comment by paulbreuler** [comment]
Export the solutions (https://dev.azure.com/PowerPlatform-ALM/_git/WS-11122?path=/.pipelines/templates/jobs/export-solution.yml)
```
      - task: PowerPlatformExportSolution@0
        inputs:
          authenticationType: "PowerPlatformSPN"
          PowerPlatformSPN: ${{ parameters.targetEnvironment }}
          SolutionName: "${{ parameters.solutionName }}"
          ${{ if eq(parameters.managed, 'false') }}:
            SolutionOutputFile: '"$(Pipeline.Workspace)/solution-export/${{ parameters.solutionName }}.zip"'
          ${{ else }}:
            SolutionOutputFile: "$(Pipeline.Workspace)/solution-export/${{ parameters.solutionName }}_managed.zip"
          Managed: ${{ parameters.managed }}
          AsyncOperation: true
          MaxAsyncWaitTime: "60"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Pipeline.Workspace)/solution-export/"
          ${{ if eq(parameters.managed, 'false') }}:
            artifact: "solution_${{ parameters.solutionName }}_unmanaged"
          ${{ else }}:
            artifact: "solution_${{ parameters.solutionName }}_managed"
          publishLocation: "pipeline"

```
  Copy files to one directory before unpack (https://dev.azure.com/PowerPlatform-ALM/_git/WS-11122?path=/.pipelines/templates/jobs/commit-solution.yml
```
      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Pipeline.Workspace)/solution_${{ parameters.solutionName }}_managed"
          Contents: "**/*.zip"
          TargetFolder: "$(Pipeline.Workspace)/solution_${{ parameters.solutionName }}_unmanaged"
```

With the files in the same location PowerPlatformUnpackSolution should just need the input file absolute path such as the following.

```
SolutionInputFile: "$(Pipeline.Workspace)/solution_${{ parameters.solutionName }}_unmanaged/${{ parameters.solutionName }}.zip"
```

Of course, you can put the files in any directory you wish just so long as both reside in the same directory.
