### ISSUE TITLE
How to make PowerPlatformCreateEnvironment@2 work with SPN users

### ISSUE THREAD

**Issue by SiPurdy** [microsoft/powerplatform-build-tools#277]
How are we supposed to use PowerPlatformCreateEnvironment@2 with Application Id and client secret based SPN users?

I'm using the same service connection that I've used with Backup and restores with the following task:
``` yaml
- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.create-environment.PowerPlatformCreateEnvironment@2
  displayName: 'Power Platform Create Environment '
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: '[REDACTED]'
    DisplayName: 'DevOps Pipeline - $(Build.BuildNumber)'
    AppsTemplate: 'D365_SalesPro'
    LocationName: unitedkingdom
    CurrencyName: GBP
    DomainName: '[REDACTED]-$(Build.BuildNumber)'
```
When run it's just outputting the following:
``` text
Creating Sandbox Dataverse database in your tenant.
Microsoft PowerPlatform CLI
Version: 1.21.5+ge089c16

Error: You do not have the required Dynamics 365 licenses to create databases with the 'Sales Pro' Dynamics app.
```
Were in a situation where Managed Identities aren't going to work (DevOps is in a different AAD tenant to Dynamics).

Any thoughts/ideas?

Thanks
