### ISSUE TITLE
MaxAsyncWaitTime is ignored when publishing

### ISSUE THREAD

**Issue by randombyte-developer** [microsoft/powerplatform-build-tools#295]
Hi!

I use this task

```
  - task: PowerPlatformPublishCustomizations@2
    displayName: "Publish customizations"
    inputs:
      authenticationType: PowerPlatformSPN
      PowerPlatformSPN: "${{ parameters.serviceConnectionName }}"
      AsyncOperation: true
      MaxAsyncWaitTime: "10"
```

but when executing it says

```
[ '\'***\' authenticated successfully.' ]
[ 'Validating connection...' ]
[ 'Connected to... ***' ]
[ 'Connected as ***' ]
[ 'Authentication profile created' ]
[ '    * DATAVERSE                                *** : ***     Public' ]
[ '' ]
[ 'The Authentication Result: \'***\' authenticated successfully.,Validating connection...,Connected to...***,Connected as ***,Authentication profile created,    * DATAVERSE                               ***: ***     Public,' ]
##[debug]AsyncOperation=true
[ 'Calling pac cli inputs: solution publish --async true' ]
##[debug]command: D:\a\_tasks\PowerPlatformToolInstaller_8015465b-f367-4ec4-8215-8edf682574d3\2.0.17\bin\pac\tools\pac.exe, first arg of 4: solution
[ 'Connected to... ***' ]
[ 'Connected as ***' ]

```

I guess there should be an additional debug line like

```
##[debug]MaxAsyncWaitTime=10
```

but it never appears.
