### ISSUE TITLE
Timeout when importing solution

### ISSUE THREAD

**Issue by cdj-unitit** [microsoft/powerplatform-build-tools#308]
When I try to deploy our solution to another environment I get the following error:

Error: The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.

My yaml code is very simple, like this:
```
- name: Import Solution
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{secrets.ENVIRONMENT_URL_TEST}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-file: 'out/solution.zip'
```

I cannot find a way to increase the timeout value
