### ISSUE TITLE
"ConvertToManaged" does not seem to be working properly.

### ISSUE THREAD

**Issue by koruneko** [microsoft/powerplatform-build-tools#659]
I exported the Unmanaged Solution from the development environment and Unpack as follows.

```yaml
steps:
- task: PowerPlatformExportSolution@2
  displayName: 'Power Platform Export Solution'
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'Dev'
    SolutionName: '$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName).zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
    Managed: false
    ExportCustomizationSettings: true
    ExportExternalApplicationSettings: true
    ExportGeneralSettings: true
    ExportAutoNumberingSettings: true
    ExportRelationshipRoles: true

- task: PowerPlatformUnpackSolution@2
  displayName: 'Power Platform Unpack Solution'
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.SourcesDirectory)/$(SolutionName)'
    SolutionType: Unmanaged
```

I then pack the Solution as follows and import it into the production environment with the "ConvertToManaged" property set to `true`.

```yaml
steps:
- task: PowerPlatformPackSolution@2
  displayName: 'Power Platform pack Solution'
  inputs:
    SolutionSourceFolder: '$(Build.SourcesDirectory)/$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName).zip'

- task: PowerPlatformImportSolution@2
  displayName: 'Power Platform Import Solution'
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'Prod'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName).zip'
    ConvertToManaged: true
    SkipProductUpdateDependencies: true
    OverwriteUnmanagedCustomizations: true
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
    PublishWorkflows: true
    UseDeploymentSettingsFile: true
    DeploymentSettingsFile: 'Settings/DeploymentSettings-Prod.json'
```

I expected this to import the Managed Solution into the production environment, but it imported it as an Unmanaged Solution.
