### ISSUE TITLE
Importing solution with deployment settings file does not update environment variable

### ISSUE THREAD

**Issue by jrossstocholm** [microsoft/powerplatform-build-tools#689]
We have a model-driven Power App that we move from DEV/TEST to STAGING to PROD using Azure pipelines.

The solution is exported as "managed" and this managed solution is then deployed to STAGING subsequently to PROD.

We have a single environment variable that needs to be updated when importing to STAGING/PROD. We have created a deployment settings file with this content:

```
{
    "EnvironmentVariables": [
      {
        "SchemaName": "gp_WebAPIURI",
        "Value": "https://org0_staging.api.crm4.dynamics.com"
      }
    ]
  }
```
We have configured the "Solution Import" task like this:

```
- task: PowerPlatformImportSolution@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'app STAGING'
    SolutionInputFile: 'D:\a\1\s\solution_managed.zip'
    #SolutionInputFile: '$(Pipeline.Workspace)/app_managed/solution_managed.zip'
    AsyncOperation: false
    ConvertToManaged: false
    UseDeploymentSettingsFile: true
    DeploymentSettingsFile: 'D:/A/1/app_managed/s/pipelines/deployment-settings_staging.json'
- task: PowerPlatformPublishCustomizations@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'app STAGING'
    #Environment: '$(BuildTools.EnvironmentUrl)'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
```

The Import task is finished successfully and we can see in the logs that the deployment settings file is loaded

```
##[debug]UseDeploymentSettingsFile=true
##[debug]DeploymentSettingsFile=D:\A\1\app_managed\s\pipelines\deployment-settings_staging.json
```

`  'Calling pac cli inputs: solution import --path D:\\a\\1\\s\\app_managed.zip --async false --force-overwrite false --publish-changes false --skip-dependency-check false --convert-to-managed false --max-async-wait-time 60 --activate-plugins true --skip-lower-version false --settings-file D:\\A\\1\\app_managed\\s\\pipelines\\deployment-settings_staging.json --log-to-console'`

```
[ 'info: bolt.cli.CommandProcessor[0]' ]
[ '      StartExecutingVerb (Verbs: ["solution","import"])' ]
[ 'info: bolt.cli.Verb[0]' ]

[
  "      Executing verb 'solution import' with arguments --path,--async,--force-overwrite,--publish-changes,--skip-dependency-check,--convert-to-managed,--max-async-wait-time,--activate-plugins,--skip-lower-version,--settings-file."
]
```

But nothing happens - the environment variable is not updated with the new value.

I am kind of at a loss here - I cannot figure out why it is not updated as per the configuration.

What am I doing wrong here?

Thanks 😊
