### ISSUE TITLE
Power Platform Import Solution option StageAndUpgrade does not stage solution for upgrade

### ISSUE THREAD

**Issue by CoreySutton** [microsoft/powerplatform-build-tools#726]
When using build task `Power Platform Import Solution` with option `StageAndUpgrade` set to `true`, solution is not staged for import, and no upgrade is applied to solution.

Image below shows:
1. YELLOW - Imported solution using PP build tools in ADO pipelines using `StageAndUpgrade` set to `true
2. RED - Imported solution using classic UI, staging solution for upgrade, then applying upgrade

![image](https://github.com/microsoft/powerplatform-build-tools/assets/5017826/4b534352-2373-4224-94cf-ec85e55a338a)

## Pipeline Step config
```yml
  - task: PowerPlatformImportSolution@2
    displayName: 'Importing Holding Solution: ${{ parameters.solution }}'
    condition: xxx
    inputs:
      authenticationType: xxx
      PowerPlatformSPN: xxx
      SolutionInputFile: 'xxx'
      AsyncOperation: true
      MaxAsyncWaitTime: '60'
      OverwriteUnmanagedCustomizations: true
      StageAndUpgrade: true
      SkipLowerVersion: true
      ConvertToManaged: true
      PublishCustomizationChanges: true 
```

Either the `StageAndUpgrade` option is not working or we have implemented it incorrectly.
